### ISSUE TITLE
Not possible to add a new annotation inside an old annotation on the iPad

### ISSUE THREAD

**Issue by astoun** [aron/annotator.touch.js#7]
If I try to add a new annotation inside of an old annotation on desktop it's working properly but on the Ipad (or with ?force) it's not.
When I click on the "Annotate"-button, nothing happens.
I've made a screenshot to explain it better.
![annotation](https://cloud.githubusercontent.com/assets/9988116/5227155/c9ab234a-76f7-11e4-9a91-b1bd9f141469.png)

Need your help! :)

**Comment by aron** [comment]
Sorry for the very slow reply. This is actually a bug in Annotator, it was reported here https://github.com/openannotation/annotator/issues/466 and was fixed here https://github.com/openannotation/annotator/pull/480. I think there'll likely be a new release in the near future, in the meantime you could use a build of the 1.2.x branch.
