### ISSUE TITLE
Undefined is not a function on line (6)

### ISSUE THREAD

**Issue by GTRS-poliba** [aron/annotator.touch.js#8]
Hi.
In accordance with title.

This is my code:

	<head>
		<link rel="stylesheet" href="css/annotator.min.css"/>
		<link rel="stylesheet" href="css/annotator.touch.css"/>
		<script type="text/javascript" src="js/jquery.js"></script>
		<script type="text/javascript" src="js/annotator-full.min.js"></script>
		<script type="text/javascript" src="js/annotator.touch.min.js"></script>
		
		<script type="text/javascript">
			$(document).ready(function()
			{
				var ann = jQuery("body").annotator();
				ann.annotator("addPlugin","Touch");
			});			
		</script>
	</head>
		<div>
			Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet 
		</div>
Any suggest?

**Comment by aron** [comment]
Hi, could you create an example on http://jsbin.com that shows the issue and I'll look into it. Thanks.

**Comment by GTRS-poliba** [comment]
http://jsbin.com/lemidequhe/4/

Thanks

**Comment by aron** [comment]
Ah, you're using an older version of the plugin (v1.0.1) please download the [latest](https://github.com/aron/annotator.touch.js/releases/tag/v1.1.1) version, that should fix the issue.

**Comment by GTRS-poliba** [comment]
Ok.
Works fine.

But update https://github.com/aron/annotator.touch.js/downloads page or README.md, please

Thanks

**Comment by aron** [comment]
Oh I'm sorry, I didn't realise GitHub had moved the download page. I'll update it immediately.

**Comment by aron** [comment]
Fixed by 456efb843fea6ba9eb9b6851b4d2dea80be4b9d0
